version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/workspace:cached
      - app-node-modules:/workspace/node_modules
    command: sleep infinity

volumes:
  app-node-modules: